dwd_tongji:
    resource: "@DWDTongjiBundle/Controller/"
    type:     annotation

dwd_data:
    resource: "@DWDDataBundle/Controller/"
    type:     annotation
    prefix:   /

#dwd_demo_admin:
#    resource: "@DWDCSAdminBundle/Controller/"
#    type:     annotation

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

homepage:
    pattern:    /
    defaults: { _controller: DWDTongjiBundle:Analyse:index }