parameters:
    pdo.db_options:
        db_table:    sessions
        db_id_col:   sess_id
        db_data_col: sess_data
        db_time_col: sess_time
        db_lifetime_col: sess_lifetime

services:
    pdo:
        class: PDO
        arguments:
            - "mysql:host=%database_host%;port=%database_port%;dbname=%database_name%"
            - "%database_user%"
            - "%database_password%"
        calls:
            - [setAttribute, [3, 2]]

    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments: ["@pdo", "%pdo.db_options%"]